services:
  # MongoDB Replica Set
  mongo1:
    image: mongo:6.0
    container_name: cigarunderground-mongo1
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27020:27017"
    volumes:
      - mongo1_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cigarunderground-network

  mongo2:
    image: mongo:6.0
    container_name: cigarunderground-mongo2
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27021:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - cigarunderground-network

  mongo3:
    image: mongo:6.0
    container_name: cigarunderground-mongo3
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27022:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - cigarunderground-network

  # Redis for GraphQL subscriptions
  redis:
    image: redis:7-alpine
    container_name: cigarunderground-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - cigarunderground-network
    command: redis-server --appendonly yes

  # CigarUnderground Backend API
  cigarunderground-backend:
    build:
      context: ./enatega-multivendor-backend
      dockerfile: Dockerfile
    container_name: cigarunderground-backend
    ports:
      - "10702:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/cigarunderground?replicaSet=rs0
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-for-production}
      JWT_EXPIRES_IN: 7d
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY:-}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL:-}
      AGE_VERIFICATION_ENABLED: true
      MINIMUM_AGE_TOBACCO: 21
      MINIMUM_AGE_ALCOHOL: 21
      VERIFICATION_EXPIRY_MONTHS: 24
      MAX_UPLOAD_SIZE_MB: 5
      CORS_ORIGIN: https://admin.cigarunderground.org,https://cigarunderground.org,http://localhost:3000
      GRAPHQL_PLAYGROUND: true
      GRAPHQL_INTROSPECTION: true
    volumes:
      - ./enatega-multivendor-backend/uploads:/app/uploads
      - ./enatega-multivendor-backend/logs:/app/logs
    networks:
      - cigarunderground-network
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - redis
      - mongo-setup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # CigarUnderground Admin Panel
  cigarunderground-admin:
    build:
      context: ./enatega-multivendor-admin
      dockerfile: Dockerfile
    container_name: cigarunderground-admin
    ports:
      - "10701:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_GRAPHQL_URL: https://api.cigarunderground.org/graphql
      NEXT_PUBLIC_GRAPHQL_WS_URL: wss://api.cigarunderground.org/graphql
      NEXT_PUBLIC_API_URL: https://api.cigarunderground.org
    networks:
      - cigarunderground-network
    depends_on:
      - cigarunderground-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Replica Set Initialization
  mongo-setup:
    image: mongo:6.0
    container_name: cigarunderground-mongo-setup
    networks:
      - cigarunderground-network
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/setup-replica-set.js:/setup-replica-set.js:ro
    command: >
      bash -c "
        sleep 30 &&
        mongosh --host mongo1:27017 --file /setup-replica-set.js
      "
    restart: "no"

  # Nginx Reverse Proxy for main site
  cigarunderground-web:
    image: nginx:alpine
    container_name: cigarunderground-web
    ports:
      - "10700:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - cigarunderground-network
    restart: unless-stopped

volumes:
  mongo1_data:
    driver: local
  mongo2_data:
    driver: local
  mongo3_data:
    driver: local
  redis_data:
    driver: local

networks:
  cigarunderground-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16